=== carlosmarin/atom-nuke/container/src/main/resources/META-INF/schema/nuke-cfg.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified"
           targetNamespace="http://atomnuke.org/configuration"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
           xmlns:jx="http://jpserver.net/jx"
           xmlns:nuke="http://atomnuke.org/configuration"
           xmlns:html="http://www.w3.org/1999/xhtml"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <!-- jaxb:extensionBindingPrefixes="jx" -->

   <!-- Enumeration and SimpleType definitions -->

   <xs:simpleType name="TimeUnitType">
      <xs:restriction base="xs:string">
         <xs:enumeration value="NANOSECONDS" />
         <xs:enumeration value="MICROSECONDS" />
         <xs:enumeration value="MILLISECONDS" />
         <xs:enumeration value="SECONDS" />
         <xs:enumeration value="MINUTES" />
         <xs:enumeration value="HOURS" />
         <xs:enumeration value="DAYS" />
      </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="LanguageType">
      <xs:restriction base="xs:string">
         <xs:enumeration value="java" />
         <xs:enumeration value="python" />
         <xs:enumeration value="javascript" />
      </xs:restriction>
   </xs:simpleType>

   <!-- Configuration ComplexType definitions -->
   <xs:element name="nuke" type="nuke:ServerConfiguration" />

   <xs:complexType name="Parameters">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:sequence>
         <xs:element name="param" type="nuke:Parameter" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="Parameter">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:attribute name="name" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>

      <xs:attribute name="value" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>

   <xs:complexType name="ServerConfiguration">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:all>
         <xs:element name="actors" type="nuke:MessageActors" minOccurs="0" maxOccurs="1" />
         <xs:element name="message-sources" type="nuke:MessageSources" minOccurs="0" maxOccurs="1" />
         <xs:element name="bindings" type="nuke:Bindings" minOccurs="0" maxOccurs="1" />
      </xs:all>
   </xs:complexType>

   <xs:complexType name="PollingInterval">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:attribute name="value" type="xs:long" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>

      <xs:attribute name="unit" type="nuke:TimeUnitType" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>

   <xs:complexType name="MessageActorDefinition">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:sequence>
         <xs:element name="parameters" type="nuke:Parameters" minOccurs="0" maxOccurs="1" />
      </xs:sequence>

      <xs:attribute name="id" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>

      <xs:attribute name="type" type="nuke:LanguageType" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>

      <xs:attribute name="href" type="xs:anyURI" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>

   <xs:complexType name="MessageActors">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:sequence>
         <xs:element name="actor" type="nuke:MessageActor" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="MessageActor">
      <xs:complexContent>
         <xs:extension base="nuke:MessageActorDefinition">
            <xs:annotation>
               <xs:documentation>
                  <html:p>
                  </html:p>
               </xs:documentation>
            </xs:annotation>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>

   <xs:complexType name="MessageSources">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:sequence>
         <xs:element name="source" type="nuke:MessageSource" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="MessageSource">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:sequence>
         <xs:element name="polling-interval" type="nuke:PollingInterval" minOccurs="0" maxOccurs="1" />
      </xs:sequence>

      <xs:attribute name="actor-ref" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>

   <xs:complexType name="Bindings">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:sequence>
         <xs:element name="binding" type="nuke:Binding" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="Binding">
      <xs:annotation>
         <xs:documentation>
            <html:p>
            </html:p>
         </xs:documentation>
      </xs:annotation>

      <xs:attribute name="id" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>

      <xs:attribute name="sink-actor" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>

      <xs:attribute name="source-actor" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation>
               <html:p>
               </html:p>
            </xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
</xs:schema>

=== carlosmarin/atom-nuke/container/src/main/resources/META-INF/schema/examples/atombus.cfg.xml
<?xml version="1.0" encoding="UTF-8"?>

<nuke xmlns='http://atomnuke.org/configuration'
      xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
      xsi:schemaLocation='http://atomnuke.org/configuration ../nuke-cfg.xsd'>

   <actors>
      <actor id="" type="" href="">
         <parameters>
            <param name="" value=""></param>
            <param name="" value=""></param>
            <param name="" value=""></param>
         </parameters>
      </actor>

      <actor id="" type="" href="">
         <parameters>
         </parameters>
      </actor>

      <actor id="" type="" href="">
         <parameters>
         </parameters>
      </actor>
   </actors>

   <bindings>
      <binding id="" sink-actor="" source-actor=""></binding>
      <binding id="" sink-actor="" source-actor=""></binding>
      <binding id="" sink-actor="" source-actor=""></binding>
   </bindings>
</nuke>
